export const transactionSample = [
	{
		id: 371,
		interaction_type_id: 117,
		behavior: 1,
		label: "Request E-value",
		label_i18n: "Request E-value",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "account-balance-wallet",
		imp: 1,
	},
	{
		id: 491,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids:
			"315,92,773,324,774,746,759,760,316,778,302,281,643,775,647,172,776,22,263,821,777,822",
		label: "Load E-value",
		label_i18n: "Load E-value",
		category: "E-Value",
		history_label: "Deposit",
		description:
			"Load value using various modes like from distributors, UPI, Card, Net-banking, etc",
		help_media_urls: "2nMHiLXZcx4",
		is_visible: 1,
		is_customer_visible: 1,
		icon: "account-balance-wallet",
	},
	{
		id: 263,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "265,266,171",
		label: "Get Business Loan",
		label_i18n: "Get Business Loan",
		category: "E-Value",
		description: "Get loan for your business instantly",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "loan",
		imp: 1,
		crm_meta:
			'{"deals":[{"type":"Onboarding", "prod": 10000007, "layout": "201492000000233001", "start_int_id": [263], "steps":{"263": "Get Business Loans Section Entered", "266":"Loan Status and Pre Approved Offers Entered","683":"Personal Details Entered", "681": "Business Details Entered", "682": "References", "687": "Document Upload Entered", "708": "Aadhaar XML Entered", "740": "E NACH Entered", "688": "E Sign Entered"}, "last_steps": {"690": "Journey Done_Lending"}}]}',
	},
	{
		id: 28,
		interaction_type_id: 96,
		behavior: 1,
		label: "Cancel E-value Request",
		label_i18n: "Cancel E-value Request",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 43,
		interaction_type_id: 169,
		behavior: 1,
		label: "Search E-value",
		label_i18n: "Search E-value",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 65,
		interaction_type_id: 191,
		behavior: 1,
		label: "Email Statement",
		label_i18n: "Email Statement",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 44,
		interaction_type_id: 0,
		behavior: 2,
		label: "E-value History",
		label_i18n: "E-value History",
		category: "E-Value",
		description: "Check your recent e-value requests",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "history",
	},
	{
		id: 63,
		interaction_type_id: 1,
		behavior: 1,
		label: "Transfer",
		label_i18n: "Transfer",
		category: "E-Value",
		history_label: "Deposit",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 92,
		interaction_type_id: 423,
		behavior: 4,
		label: "Cash Deposit",
		label_i18n: "Cash Deposit",
		category: "E-Value",
		description: "Load E-value by depositing cash into Eko’s bank account",
		help_media_urls:
			"https://files.eko.co.in/docs/Cashdepositslip/cash_deposit_slips.png",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 171,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "267,319",
		label: "Manage My Loan",
		label_i18n: "Manage My Loan",
		category: "E-Value",
		description: "Check your repayments and drawdown request",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "settings",
	},
	{
		id: 692,
		interaction_type_id: 572,
		behavior: 1,
		label: "Make New Investment",
		label_i18n: "Make New Investment",
		category: "E-Value",
		description: "Invest your money and earn profit",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "business-center",
	},
	{
		id: 693,
		interaction_type_id: 574,
		behavior: 1,
		label: "Manage My Investment",
		label_i18n: "Manage My Investment",
		category: "E-Value",
		description: "Manage your invested money",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "settings",
	},
	{
		id: 698,
		interaction_type_id: 523,
		behavior: 1,
		label: "Upload Your PAN Card",
		label_i18n: "Upload your pan card",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 699,
		interaction_type_id: 571,
		behavior: 1,
		label: "Fetching Recipients",
		label_i18n: "Fetching Recipients",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 700,
		interaction_type_id: 570,
		behavior: 1,
		label: "Bank Details",
		label_i18n: "Bank Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 701,
		interaction_type_id: 573,
		behavior: 1,
		label: "Confirm Your Investment Details",
		label_i18n: "Confirm Your Investment Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 702,
		interaction_type_id: 0,
		behavior: 3,
		label: "Do you want to change your PAN Card",
		label_i18n: "Do you want to change your PAN Card",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 703,
		interaction_type_id: 575,
		behavior: 1,
		label: "Withdrawal",
		label_i18n: "Withdrawal",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money-note",
	},
	{
		id: 704,
		interaction_type_id: 575,
		behavior: 1,
		label: "Re-Invest",
		label_i18n: "Re-Invest",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 224,
		interaction_type_id: 548,
		behavior: 1,
		label: "Agreement",
		label_i18n: "Agreement",
		category: "Registration",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 645,
		interaction_type_id: 0,
		behavior: 1,
		label: "LIC Bill Payment",
		label_i18n: "LIC Bill Payment",
		category: " ",
		description: "Pay your LIC Premium Instantly",
		help_media_urls:
			"https://files.eko.co.in/docs/ekostore/brands/lic-insurance/poster1.png,https://files.eko.co.in/docs/ekostore/brands/lic-insurance/poster3.png",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "emi",
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/lic-insurance/logo.png",
		logo: "https://files.eko.co.in/docs/ekostore/brands/lic-insurance/logo.png",
		released_days_ago: 88,
	},
	{
		id: 657,
		interaction_type_id: 391,
		behavior: 1,
		label: "Aadhaar Pay",
		label_i18n: "Aadhaar Pay",
		category: " ",
		description: "Provide payment services using Aadhaar to your customers",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "account-balance-wallet",
		released_days_ago: 88,
	},
	{
		id: 715,
		interaction_type_id: 0,
		behavior: 5,
		label: "Loan Application Status",
		label_i18n: "Loan Application Status",
		category: "Registration",
		is_visible: 0,
		is_customer_visible: 0,
		logo: "https://files.eko.co.in/docs/Loan/Logo/10.png",
	},
	{
		id: 689,
		interaction_type_id: 523,
		behavior: 1,
		label: "Upload Document",
		label_i18n: "Upload Document",
		category: "Registration",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
		logo: "https://files.eko.co.in/docs/Loan/Logo/4.png",
	},
	{
		id: 336,
		interaction_type_id: 483,
		behavior: 1,
		label: "Process Claim",
		label_i18n: "Process Claim",
		category: "Registration",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 268,
		interaction_type_id: 150,
		behavior: 1,
		label: "Prabhu Shriram Agarbatti",
		label_i18n: "Prabhu Shriram Agarbatti",
		category: "EkoStore",
		description: "Buy Products Online",
		help_media_urls:
			"ekostore://brands/prabhu-shriram-agarbatti/logo.png,ekostore://brands/prabhu-shriram-agarbatti/images.jpg,ekostore://brands/prabhu-shriram-agarbatti/logo1.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo2.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo3.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo4.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo5.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo6.jpeg,ekostore://brands/prabhu-shriram-agarbatti/logo7.jpeg",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/prabhu-shriram-agarbatti/logo.png",
		brand_category_ids: "4,17",
		imp: 1,
		crm_meta:
			'{"deals":[\n{"type":"Prabhu Shriram Agarbatti", "prod": 101, "layout": "201492000000233001", "start_int_id": [268], "steps":{"268":"Search Customer","259":"Customer Details", "260": "Verify Customer", "269": "Product Details", "837": "Fetch Delivery Address", "838": "Confirm Your Delivery Address", "839": "Edit Your Delivery Address", "840": "New Delivery Address"}, "last_steps": {"841": "Journey Done"}}\n]}',
	},
	{
		id: 269,
		interaction_type_id: 0,
		behavior: 3,
		label: "Product Details",
		label_i18n: "Product Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 293,
		interaction_type_id: 0,
		behavior: 2,
		label: "Get Business Loan",
		label_i18n: "Get Business Loan",
		category: "EkoStore",
		description: "Avail working capital loan in just a few clicks",
		help_media_urls:
			"VV63JIE3Sco|EkoStore में आपका स्वागत है,Yc0y4ZjMMJU|How To Apply For Loan?,RRC6ZS-LVII,ZRX1AbNs0ZA,https://files.eko.co.in/docs/Loan/lending_poster.png,https://files.eko.co.in/docs/Loan/lending_poster1.png,https://files.eko.co.in/docs/Loan/lending_poster2.png,https://files.eko.co.in/docs/Loan/lending_poster3.png",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		imp: 1,
	},
	{
		id: 323,
		interaction_type_id: 449,
		behavior: 1,
		label: "Buy TubeNight Subscription",
		label_i18n: "Buy TubeNight Subscription",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/TubeNight/Tubenight_logo.jpg",
		imp: 1,
	},
	{
		id: 331,
		interaction_type_id: 150,
		behavior: 1,
		label: "Search Token Customer",
		label_i18n: "Search Token Customer",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 344,
		interaction_type_id: 150,
		behavior: 1,
		label: "Edelweiss Group Total Protect Policy",
		label_i18n: "Edelweiss Group Total Protect Policy",
		category: "EkoStore",
		description:
			"₹2 Lac accidental death cover & more @ ₹299/year. T&Cs Apply",
		help_media_urls:
			"SG-2l3fFiKI|Edelweiss पॉलिसी के फायदे,5j5eT-qeKno|Benefits of Edelweiss Policy,brands://edelweiss/edelweiss_poster.jpg,sFG_okG9274|How To Sell Edelweiss Policy,brands://edelweiss/edelweiss_poster-01.jpg,brands://edelweiss/edelweiss_poster-02.jpg,brands://edelweiss/edelweiss_poster-03.jpg,brands://edelweiss/edelweiss_poster-04.jpg,brands://edelweiss/edelweiss_poster-05.jpg",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/edelweiss/edelweiss.png",
		brand_category_ids: "6,13",
		imp: 1,
	},
	{
		id: 346,
		interaction_type_id: 0,
		behavior: 1,
		label: "Buy Edelweiss Insurance",
		label_i18n: "Buy Edelweiss Insurance",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 347,
		interaction_type_id: 0,
		behavior: 1,
		label: "Buy Edelweiss Insurance",
		label_i18n: "Buy Edelweiss Insurance",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 407,
		interaction_type_id: 150,
		behavior: 1,
		label: "PM CARES FUND",
		label_i18n: "PM CARES FUND",
		category: "EkoStore",
		description:
			"Donate for collective fight against the coronavirus (COVID-19) pandemic",
		help_media_urls: "brands://Donation/PM-CARES-FUND.jpg",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/Donation/PM-CARES-Logo.jpg",
	},
	{
		id: 409,
		interaction_type_id: 221,
		behavior: 1,
		label: "Donate",
		label_i18n: "Donate",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 437,
		interaction_type_id: 0,
		behavior: 5,
		label: "PM SVANidhi Loan",
		label_i18n: "PM SVANidhi Loan",
		category: "EkoStore",
		description:
			"Special loan for street vendors. Loan amount upto ₹10,000",
		help_media_urls:
			"brands://PM-SVANidhi/loan-details.jpg,brands://PM-SVANidhi/process.jpg",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/logos/PM-SVANidhi_Scheme.png",
		brand_category_ids: "6",
	},
	{
		id: 472,
		interaction_type_id: 0,
		behavior: 2,
		label: "Instant Weekend Loans",
		label_i18n: "Instant Weekend Loans",
		category: "EkoStore",
		description: "Don't want to stop business on bank holidays? Avail Now!",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 562,
		interaction_type_id: 379,
		behavior: 1,
		label: "DMI Finance",
		label_i18n: "DMI Finance",
		category: "EkoStore",
		description: "Pay monthly EMI for DMI Loans",
		help_media_urls:
			"https://files.eko.co.in/docs/notification/image_1545299845655_3384.png",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "emi",
		ext_icon: "images/brands/dmi.png",
		brand_category_ids: "6,16",
	},
	{
		id: 570,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "571",
		label: "Insurance",
		label_i18n: "Insurance",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 572,
		interaction_type_id: 10041,
		behavior: 1,
		label: "RenewBuy Insurance",
		label_i18n: "RenewBuy Insurance",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 600,
		interaction_type_id: 449,
		behavior: 1,
		label: "Shemaroo Bhakti",
		label_i18n: "Shemaroo Bhakti",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 658,
		interaction_type_id: 624,
		behavior: 1,
		label: "Confirm Your Delivery Address",
		label_i18n: "Confirm Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 802,
		interaction_type_id: 588,
		behavior: 1,
		label: "Apply for Job",
		label_i18n: "Apply for Job",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 803,
		interaction_type_id: 591,
		behavior: 1,
		label: "Job Details",
		label_i18n: "Job Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "access-time",
	},
	{
		id: 804,
		interaction_type_id: 589,
		behavior: 1,
		label: "Update Job Status",
		label_i18n: "Update Job Status",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 809,
		interaction_type_id: 0,
		behavior: 3,
		label: "Job Done",
		label_i18n: "Job Done",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 810,
		interaction_type_id: 586,
		behavior: 1,
		label: "My Jobs",
		label_i18n: "My Jobs",
		category: "EkoStore",
		description: "List of my active jobs",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "toc",
	},
	{
		id: 838,
		interaction_type_id: 624,
		behavior: 1,
		label: "Confirm Your Delivery Address",
		label_i18n: "Confirm Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 873,
		interaction_type_id: 150,
		behavior: 1,
		label: "Search Customer",
		label_i18n: "Search Customer",
		category: "EkoStore",
		description:
			"With Airtel's cash Management System, make payment for hundreds of products",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon: "images/brands/airtel.jpg",
		brand_category_ids: "16",
	},
	{
		id: 875,
		interaction_type_id: 0,
		behavior: 5,
		label: "Airtel CMS",
		label_i18n: "Airtel CMS",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 880,
		interaction_type_id: 0,
		behavior: 1,
		label: "Proceed",
		label_i18n: "Proceed",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 252,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "481,626,636,819,175",
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "EkoStore",
		description:
			"Provide cash withdrawal services using Aadhaar to your customers",
		help_media_urls:
			"logos://aeps/offer1.png,https://files.eko.co.in/docs/notification/image_1524288984538_1491.png,https://files.eko.co.in/docs/notification/image_1523965851513_4640.jpg,https://files.eko.co.in/docs/notification/image_1528367534103_2082.png",
		earn: "Upto ₹12",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "cashout",
		ext_icon: "images/brands/aeps_logo.png",
		brand_category_ids: "6",
		imp: 1,
		crm_meta:
			'{"deals":[\n{"type":"Onboarding", "prod": 100, "layout": "201492000000233001", "start_int_id": [624,626], "steps":{"624":"Check Device Availability Entered","625":"Purchase Device Entered", "518": "Device Registration & Setup Entered", "614": "KYC Entered"}, "last_steps": {"616": "Journey Done"}}\n]}',
	},
	{
		id: 244,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids:
			"877,645,29,677,522,521,270,271,272,273,274,275,66,706,747,705,710,711,712,713,716,714,717,718,719,720,721,722,723,724,725,726,727,728,729,733,742",
		label: "Recharge & Bill Payment",
		label_i18n: "Recharge & Bill Payment",
		category: "EkoStore",
		description:
			"Pay for Mobile, DTH, Electricity, Internet, Landline, LPG, Water, Insurance, Property & Credit Card bills",
		help_media_urls:
			"https://files.eko.co.in/docs/notification/image_1527146378271_2003.png,https://files.eko.co.in/docs/notification/image_1520334097816_772.png,https://files.eko.co.in/docs/notification/image_1549107294328_1384.png",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "smartphone",
		logo: "https://files.eko.co.in/docs/logos/utility/BBPS.png",
		brand_category_ids: "9,16",
	},
	{
		id: 208,
		interaction_type_id: 0,
		behavior: 2,
		label: "Indo-Nepal Transfer",
		label_i18n: "Indo-Nepal Transfer",
		category: "EkoStore",
		description: "Transfer money to any bank account in Nepal",
		earn: "₹40",
		is_visible: 1,
		is_customer_visible: 1,
		icon: "nepal",
		ext_icon: "images/brands/EkoIndoNepal.png",
		brand_category_ids: "6",
		imp: 1,
	},
	{
		id: 335,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "41,328",
		label: "Initiate Refund",
		label_i18n: "Initiate Refund",
		category: "EkoStore",
		description:
			"Initiate refund to customer for money-remittance, payment, etc.",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "replay",
	},
	{
		id: 246,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids:
			"877,870,871,872,268,805,252,243,597,657,208,66,754,627,438,437,344,599,330,322,571,255,562,594,595,596,592,593,429,694,249",
		label: "EkoStore",
		label_i18n: "EkoStore",
		category: "EkoStore",
		description:
			"A one-stop bazaar for insurance, online shopping, entertainment, learning, bill payments, etc",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "apps",
		imp: 1,
	},
	{
		id: 381,
		interaction_type_id: 498,
		behavior: 1,
		label: "Your Bank Account",
		label_i18n: "Your Bank Account",
		category: "EkoStore",
		description: "Accept payment from your customer with card or UPI app",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "credit-card",
	},
	{
		id: 382,
		interaction_type_id: 502,
		behavior: 1,
		label: "Your Bank Account",
		label_i18n: "Your Bank Account",
		category: "EkoStore",
		description: "Accept payment from your customer with card or UPI app",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "credit-card",
	},
	{
		id: 411,
		interaction_type_id: 502,
		behavior: 1,
		label: "Your Bank Account",
		label_i18n: "Your Bank Account",
		category: "EkoStore",
		description: "Accept payment from your customer with card or UPI app",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "credit-card",
	},
	{
		id: 412,
		interaction_type_id: 498,
		behavior: 1,
		label: "Settings & History",
		label_i18n: "Settings & History",
		category: "EkoStore",
		description: "Accept payment from your customer with card or UPI app",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "settings",
	},
	{
		id: 249,
		interaction_type_id: 0,
		behavior: 9,
		label: "Scan Token",
		label_i18n: "Scan Token",
		category: "EkoStore",
		description:
			"Scan customer's Token to make payments and earn money quickly",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "qrcode",
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/token/token.logo.2.min.svg",
		imp: 1,
	},
	{
		id: 406,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "407",
		label: "Donate",
		label_i18n: "Donate",
		category: "EkoStore",
		description: "Your donation will help someone",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 247,
		interaction_type_id: 0,
		behavior: 3,
		label: "",
		label_i18n: "",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		imp: 1,
	},
	{
		id: 519,
		interaction_type_id: 0,
		behavior: 2,
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "EkoStore",
		description:
			"Provide cash withdrawal services using Aadhaar to your customers",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "cashout",
		imp: 1,
	},
	{
		id: 383,
		interaction_type_id: 391,
		behavior: 1,
		label: "Bank Details",
		label_i18n: "Bank Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "account-balance",
	},
	{
		id: 413,
		interaction_type_id: 391,
		behavior: 1,
		label: "Bank Details",
		label_i18n: "Bank Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "account-balance",
	},
	{
		id: 384,
		interaction_type_id: 399,
		behavior: 1,
		label: "Add Account",
		label_i18n: "Add Account",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 385,
		interaction_type_id: 399,
		behavior: 1,
		label: "Add Account",
		label_i18n: "Add Account",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 659,
		interaction_type_id: 0,
		behavior: 3,
		label: "Do you know what is Aadhaar Pay (AePS) ?",
		label_i18n: "Do you know what is Aadhaar Pay (AePS) ?",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 661,
		interaction_type_id: 0,
		behavior: 3,
		label: "What is Aadhaar Pay (AePS) ?",
		label_i18n: "What is Aadhaar Pay (AePS) ?",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 170,
		interaction_type_id: 10014,
		behavior: 1,
		label: "Product Details",
		label_i18n: "Product Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 628,
		interaction_type_id: 303,
		behavior: 1,
		label: "Confirm Your Delivery Address",
		label_i18n: "Confirm Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 629,
		interaction_type_id: 556,
		behavior: 1,
		label: "New Delivery Address",
		label_i18n: "New Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 629,
		interaction_type_id: 556,
		behavior: 1,
		label: "New Delivery Address",
		label_i18n: "New Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 663,
		interaction_type_id: 0,
		behavior: 3,
		label: "Buy Your Device",
		label_i18n: "Buy Your Device",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 664,
		interaction_type_id: 0,
		behavior: 3,
		label: "Product Details",
		label_i18n: "Product Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 668,
		interaction_type_id: 556,
		behavior: 1,
		label: "Confirm Your Delivery Address",
		label_i18n: "Confirm Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 767,
		interaction_type_id: 556,
		behavior: 1,
		label: "Edit Your Delivery Address",
		label_i18n: "Edit Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 837,
		interaction_type_id: 303,
		behavior: 1,
		label: "Confirm Your Delivery Address",
		label_i18n: "Confirm Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 839,
		interaction_type_id: 556,
		behavior: 1,
		label: "Edit Your Delivery Address",
		label_i18n: "Edit Your Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 840,
		interaction_type_id: 556,
		behavior: 1,
		label: "New Delivery Address",
		label_i18n: "New Delivery Address",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 386,
		interaction_type_id: 501,
		behavior: 1,
		label: "Set Prefered Account",
		label_i18n: "Set Prefered Account",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 414,
		interaction_type_id: 501,
		behavior: 1,
		label: "Set Prefered Account",
		label_i18n: "Set Prefered Account",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 624,
		interaction_type_id: 0,
		behavior: 3,
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 660,
		interaction_type_id: 0,
		behavior: 3,
		label: "Do you have a fingerprint device ?",
		label_i18n: "Do you have a fingerprint device ?",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 636,
		interaction_type_id: 0,
		behavior: 2,
		label: "Get started with AePS",
		label_i18n: "Get started with AePS",
		category: "EkoStore",
		description:
			"Provide cash withdrawal services using Aadhaar to your customers",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "cashout",
	},
	{
		id: 387,
		interaction_type_id: 150,
		behavior: 1,
		label: "Enter Customer's Mobile",
		label_i18n: "Enter Customer's Mobile",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 625,
		interaction_type_id: 10015,
		behavior: 1,
		label: "Buy Your Device Online",
		label_i18n: "Buy Your Device Online",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 635,
		interaction_type_id: 394,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 666,
		interaction_type_id: 0,
		behavior: 5,
		label: "Buy Your Device Online",
		label_i18n: "Buy Your Device Online",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 669,
		interaction_type_id: 394,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 841,
		interaction_type_id: 394,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 398,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 631,
		interaction_type_id: 0,
		behavior: 3,
		label: "Complete Your KYC",
		label_i18n: "Complete Your KYC",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 399,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 400,
		interaction_type_id: 503,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 401,
		interaction_type_id: 505,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 402,
		interaction_type_id: 499,
		behavior: 1,
		label: "Payment Mode",
		label_i18n: "Payment Mode",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 415,
		interaction_type_id: 499,
		behavior: 1,
		label: "Payment Mode",
		label_i18n: "Payment Mode",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 415,
		interaction_type_id: 499,
		behavior: 1,
		label: "Payment Mode",
		label_i18n: "Payment Mode",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 637,
		interaction_type_id: 499,
		behavior: 1,
		label: "Payment Mode",
		label_i18n: "Payment Mode",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 670,
		interaction_type_id: 499,
		behavior: 1,
		label: "Payment Mode",
		label_i18n: "Payment Mode",
		category: "EkoStore",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 754,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "755,756",
		label: "Mool",
		label_i18n: "Mool",
		category: "EkoStore",
		history_label: "Deposit",
		description: "Deposit & withdraw cash from your Mool savings account",
		help_media_urls:
			"https://files.eko.co.in/docs/ekostore/brands/logos/moolone-poster.jpg",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "account-balance-wallet",
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/logos/moolone.svg",
		brand_category_ids: "6",
	},
	{
		id: 11,
		interaction_type_id: 83,
		behavior: 1,
		label: "Process Refund",
		label_i18n: "Process Refund",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 20,
		interaction_type_id: 98,
		behavior: 1,
		label: "Search Transaction",
		label_i18n: "Search Transaction",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 207,
		interaction_type_id: 275,
		behavior: 1,
		label: "Search Customer",
		label_i18n: "Search Customer",
		category: "Money Transfer",
		help_media_urls:
			"VV63JIE3Sco|EkoStore में आपका स्वागत है,NdXmB8SZBOo|How to Send Money to Nepal?,brands://Indo-nepal/Indo-nepal-poster.jpg",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 209,
		interaction_type_id: 278,
		behavior: 1,
		label: "Fetching Recipients",
		label_i18n: "Fetching Recipients",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 211,
		interaction_type_id: 276,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 212,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 214,
		interaction_type_id: 524,
		behavior: 1,
		label: "Enter Amount",
		label_i18n: "Enter Amount",
		category: "Money Transfer",
		history_label: "Indo-Nepal",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 301,
		interaction_type_id: 294,
		behavior: 1,
		label: "Retry",
		label_i18n: "Retry",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 306,
		interaction_type_id: 318,
		behavior: 1,
		label: "Fetching VPAs",
		label_i18n: "Fetching VPAs",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 307,
		interaction_type_id: 317,
		behavior: 1,
		label: "Add VPA",
		label_i18n: "Add VPA",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 313,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 314,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 332,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 333,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 334,
		interaction_type_id: 0,
		behavior: 1,
		label: "Pay Token",
		label_i18n: "Pay Token",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 345,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
		imp: 1,
	},
	{
		id: 403,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		history_label: "Pay with Card",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 404,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		history_label: "Pay with Card",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 408,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 410,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 416,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 424,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 442,
		interaction_type_id: 318,
		behavior: 1,
		label: "Fetching VPAs",
		label_i18n: "Fetching VPAs",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 443,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 444,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 445,
		interaction_type_id: 317,
		behavior: 1,
		label: "Add VPA",
		label_i18n: "Add VPA",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 449,
		interaction_type_id: 526,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 451,
		interaction_type_id: 277,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 476,
		interaction_type_id: 279,
		behavior: 1,
		label: "Send Cash",
		label_i18n: "Send Cash",
		category: "Money Transfer",
		history_label: "Indo-Nepal",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 485,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 494,
		interaction_type_id: 83,
		behavior: 1,
		label: "Process Withdrawal",
		label_i18n: "Process Withdrawal",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 638,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 667,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 671,
		interaction_type_id: 500,
		behavior: 1,
		label: "Payment Details",
		label_i18n: "Payment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 676,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 866,
		interaction_type_id: 645,
		behavior: 1,
		label: "Do KYC",
		label_i18n: "Do KYC",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 867,
		interaction_type_id: 646,
		behavior: 1,
		label: "Do KYC",
		label_i18n: "Do KYC",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 874,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 876,
		interaction_type_id: 103,
		behavior: 1,
		label: "Verify Customer",
		label_i18n: "Verify Customer",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 309,
		interaction_type_id: 325,
		behavior: 1,
		label: "Request Payment",
		label_i18n: "Request Payment",
		category: "Money Transfer",
		history_label: "Pay with UPI Apps",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 310,
		interaction_type_id: 326,
		behavior: 1,
		label: "Check Status",
		label_i18n: "Check Status",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 311,
		interaction_type_id: 326,
		behavior: 1,
		label: "Status",
		label_i18n: "Status",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 446,
		interaction_type_id: 325,
		behavior: 1,
		label: "Request Payment",
		label_i18n: "Request Payment",
		category: "Money Transfer",
		history_label: "Pay with UPI Apps",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 447,
		interaction_type_id: 326,
		behavior: 1,
		label: "Check Status",
		label_i18n: "Check Status",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 1115,
		interaction_type_id: 326,
		behavior: 1,
		label: "Status",
		label_i18n: "Status",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 756,
		interaction_type_id: 0,
		behavior: 2,
		label: "Withdraw Cash",
		label_i18n: "Withdraw Cash",
		category: "Money Transfer",
		help_media_urls:
			"https://files.eko.co.in/docs/ekostore/brands/logos/moolone-poster.jpg",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/logos/moolone.svg",
	},
	{
		id: 305,
		interaction_type_id: 322,
		behavior: 1,
		label: "Amount",
		label_i18n: "Amount",
		category: "Money Transfer",
		description:
			"Load E-value using your UPI apps like GPay, BHIM, Paytm, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 439,
		interaction_type_id: 322,
		behavior: 1,
		label: "Accept Payment with UPI Apps",
		label_i18n: "Accept Payment with UPI Apps",
		category: "Money Transfer",
		description:
			"Load E-value using your UPI apps like GPay, BHIM, Paytm, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 1112,
		interaction_type_id: 322,
		behavior: 1,
		label: "Amount",
		label_i18n: "Amount",
		category: "Money Transfer",
		description:
			"Load E-value using your UPI apps like GPay, BHIM, Paytm, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 267,
		interaction_type_id: 453,
		behavior: 1,
		label: "Check Repayments",
		label_i18n: "Check Repayments",
		category: "Money Transfer",
		description: "Check your pending repayments",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "emi",
		imp: 1,
	},
	{
		id: 647,
		interaction_type_id: 0,
		behavior: 2,
		label: "AePS Pay",
		label_i18n: "AePS Pay",
		category: "Money Transfer",
		description: "Load E-value using your AePS",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "qrcode",
	},
	{
		id: 877,
		interaction_type_id: 0,
		behavior: 2,
		label: "Airtel CMS",
		label_i18n: "Airtel CMS",
		category: "Money Transfer",
		description: "Load E-value using your AePS",
		is_visible: 0,
		is_customer_visible: 1,
		ext_icon: "images/brands/airtel.jpg",
	},
	{
		id: 319,
		interaction_type_id: 263,
		behavior: 1,
		label: "Raise Drawdown Request",
		label_i18n: "Raise Drawdown Request",
		category: "Money Transfer",
		description: "Simple steps to Drawdown/Withdraw your loan",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 538,
		interaction_type_id: 561,
		behavior: 1,
		label: "Drawdown Request",
		label_i18n: "Drawdown Request",
		category: "Money Transfer",
		description: "Simple steps to Drawdown/Withdraw your loan",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 730,
		interaction_type_id: 578,
		behavior: 4,
		label: "Download Agreement",
		label_i18n: "Download Agreement",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 731,
		interaction_type_id: 561,
		behavior: 1,
		label: "Drawdown Request",
		label_i18n: "Drawdown Request",
		category: "Money Transfer",
		description: "Simple steps to Drawdown/Withdraw your loan",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "money",
	},
	{
		id: 732,
		interaction_type_id: 579,
		behavior: 1,
		label: "Investment Details",
		label_i18n: "Investment Details",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "folder-open",
	},
	{
		id: 51,
		interaction_type_id: 172,
		behavior: 1,
		label: "Looking for Transactions",
		label_i18n: "Looking for Transactions",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 210,
		interaction_type_id: 277,
		behavior: 1,
		label: "Add Recipient",
		label_i18n: "Add Recipient",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 378,
		interaction_type_id: 310,
		behavior: 1,
		label: "Resubmit Document",
		label_i18n: "Resubmit Document",
		category: "Money Transfer",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 440,
		interaction_type_id: 344,
		behavior: 1,
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "Cash-out & Merchant Payments",
		help_media_urls:
			"HmJ6a-f2bCI,https://docs.google.com/document/u/1/d/e/2PACX-1vTWazQcB-BI5PfrJBwgfWGp7cKj3OX-yFjO4hLy_ZprOjhrSl70ftMWEFRa34t0WDuqap5boa8N_E-o/pub?embedded=true",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 483,
		interaction_type_id: 344,
		behavior: 1,
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "Cash-out & Merchant Payments",
		help_media_urls:
			"HmJ6a-f2bCI,https://docs.google.com/document/u/1/d/e/2PACX-1vTWazQcB-BI5PfrJBwgfWGp7cKj3OX-yFjO4hLy_ZprOjhrSl70ftMWEFRa34t0WDuqap5boa8N_E-o/pub?embedded=true",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 484,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 487,
		interaction_type_id: 345,
		behavior: 1,
		label: "",
		label_i18n: "",
		category: "Cash-out & Merchant Payments",
		history_label: "AePS Withdraw",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 674,
		interaction_type_id: 344,
		behavior: 1,
		label: "Aadhaar Pay",
		label_i18n: "Aadhaar Pay",
		category: "Cash-out & Merchant Payments",
		help_media_urls:
			"HmJ6a-f2bCI,https://docs.google.com/document/u/1/d/e/2PACX-1vTWazQcB-BI5PfrJBwgfWGp7cKj3OX-yFjO4hLy_ZprOjhrSl70ftMWEFRa34t0WDuqap5boa8N_E-o/pub?embedded=true",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 675,
		interaction_type_id: 110,
		behavior: 1,
		label: "Customer Details",
		label_i18n: "Customer Details",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 292,
		interaction_type_id: 0,
		behavior: 3,
		label: "To Enable Service Refresh ",
		label_i18n: "To Enable Service Refresh ",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 420,
		interaction_type_id: 514,
		behavior: 1,
		label: "Accept Now",
		label_i18n: "Accept Now",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "go",
	},
	{
		id: 481,
		interaction_type_id: 0,
		behavior: 2,
		label: "AePS Cashout",
		label_i18n: "AePS Cashout",
		category: "Cash-out & Merchant Payments",
		description:
			"Provide cash withdrawal services using Aadhaar to your customers",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "cashout",
		imp: 1,
	},
	{
		id: 312,
		interaction_type_id: 0,
		behavior: 2,
		label: "Into Your E-value Account",
		label_i18n: "Into Your E-value Account",
		category: "Cash-out & Merchant Payments",
		description: "UPI app like Google Pay, BHIM, PayTM, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "qrcode",
		imp: 1,
	},
	{
		id: 482,
		interaction_type_id: 150,
		behavior: 3,
		label: "Search Customer",
		label_i18n: "Search Customer",
		category: "Cash-out & Merchant Payments",
		help_media_urls: "logos://aeps/offer1.png",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 646,
		interaction_type_id: 344,
		behavior: 1,
		label: "Load E-value Via AePS",
		label_i18n: "Load E-value Via AePS",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 673,
		interaction_type_id: 150,
		behavior: 3,
		label: "Search Customer",
		label_i18n: "Search Customer",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 81,
		interaction_type_id: 365,
		behavior: 1,
		label: "Enable AePS",
		label_i18n: "Enable AePS",
		category: "Cash-out & Merchant Payments",
		help_media_urls: "wEjjGcv2huU",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 81,
		interaction_type_id: 365,
		behavior: 1,
		label: "Enable AePS",
		label_i18n: "Enable AePS",
		category: "Cash-out & Merchant Payments",
		help_media_urls: "wEjjGcv2huU",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 426,
		interaction_type_id: 517,
		behavior: 1,
		label: "Enable AePS",
		label_i18n: "Enable AePS",
		category: "Cash-out & Merchant Payments",
		help_media_urls: "wEjjGcv2huU",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 518,
		interaction_type_id: 365,
		behavior: 1,
		label: "Device Registration",
		label_i18n: "Device Registration",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 662,
		interaction_type_id: 557,
		behavior: 1,
		label: "Enable Aadhaar Pay",
		label_i18n: "Enable Aadhaar Pay",
		category: "Cash-out & Merchant Payments",
		help_media_urls: "wEjjGcv2huU",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 613,
		interaction_type_id: 391,
		behavior: 1,
		label: "Check Status",
		label_i18n: "Check Status",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 868,
		interaction_type_id: 543,
		behavior: 1,
		label: "Complete Biometric Process",
		label_i18n: "Complete Biometric Process",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 869,
		interaction_type_id: 647,
		behavior: 1,
		label: "Complete Basic Details",
		label_i18n: "Complete Basic Details",
		category: "Cash-out & Merchant Payments",
		is_visible: 0,
		is_customer_visible: 1,
	},
	{
		id: 639,
		interaction_type_id: 394,
		behavior: 1,
		label: "Device Purchase",
		label_i18n: "Device Purchase",
		category: "Select Plans",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "local-offer",
	},
	{
		id: 672,
		interaction_type_id: 394,
		behavior: 1,
		label: "Activation Fee",
		label_i18n: "Activation Fee",
		category: "Select Plans",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "local-offer",
	},
	{
		id: 780,
		interaction_type_id: 0,
		behavior: 1,
		label: "Pay",
		label_i18n: "Pay",
		category: "Bill Payment",
		history_label: "Bill Payment",
		is_visible: 0,
		is_customer_visible: 1,
		released_days_ago: 88,
	},
	{
		id: 283,
		interaction_type_id: 454,
		behavior: 1,
		label: "Add Account",
		label_i18n: "Add Account",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "account-balance",
	},
	{
		id: 284,
		interaction_type_id: 456,
		behavior: 1,
		label: "Request E-value from YES Bank",
		label_i18n: "Turbo E-value - YES Bank",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 806,
		interaction_type_id: 456,
		behavior: 1,
		label: "Load E-value via PhonePe",
		label_i18n: "Load E-value via PhonePe",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 807,
		interaction_type_id: 456,
		behavior: 1,
		label: "Load E-value via PayTM",
		label_i18n: "Load E-value via PayTM",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 285,
		interaction_type_id: 455,
		behavior: 1,
		label: "Account Details",
		label_i18n: "Account Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 282,
		interaction_type_id: 391,
		behavior: 1,
		label: "Request E-value from YES Bank",
		label_i18n: "Turbo E-value - YES Bank",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "flight",
	},
	{
		id: 281,
		interaction_type_id: 309,
		behavior: 1,
		label: "Turbo E-value - Axis Bank",
		label_i18n: "Turbo E-value - Axis Bank",
		category: "E-Value",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon: "https://files.eko.co.in/docs/logos/axisbank/Axis_bank.png",
	},
	{
		id: 303,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "302,281",
		label: "Turbo E-value",
		label_i18n: "Turbo E-value",
		category: "E-Value",
		history_label: "Deposit",
		description:
			"No charges. Quickly load E-value by depositing cash in your virtual account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "flight",
	},
	{
		id: 743,
		interaction_type_id: 391,
		behavior: 1,
		label: "Load E-value via PhonePe",
		label_i18n: "Load E-value via PhonePe",
		category: "E-Value",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/Evalue/load-e-value/PhonePe-Logo.png",
	},
	{
		id: 744,
		interaction_type_id: 391,
		behavior: 1,
		label: "Load E-value via PayTM",
		label_i18n: "Load E-value via PayTM",
		category: "E-Value",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/Evalue/load-e-value/Paytm-Logo.png",
	},
	{
		id: 759,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "743,318",
		label: "Load E-value via PhonePe",
		label_i18n: "Load E-value via PhonePe",
		category: "E-Value",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/Evalue/load-e-value/PhonePe-Logo.png",
	},
	{
		id: 760,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "744,318",
		label: "Load E-value via PayTM",
		label_i18n: "Load E-value via PayTM",
		category: "E-Value",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/Evalue/load-e-value/Paytm-Logo.png",
	},
	{
		id: 302,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "282,318",
		label: "Turbo E-value - YES Bank",
		label_i18n: "Turbo E-value - YES Bank",
		category: "E-Value",
		history_label: "Deposit",
		description:
			" Quickly load E-value by depositing cash in your virtual account.",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/logos/yesbank/Turbo_Yes-Bank_logo.png",
	},
	{
		id: 294,
		interaction_type_id: 259,
		behavior: 1,
		label: "Apply for Loan",
		label_i18n: "Apply for Loan",
		category: "E-Value",
		help_media_urls:
			"https://docs.google.com/presentation/d/1yS0X5OnX2e_uUxw8gi3E1WD3zwXkhzfzCihVApPpyok/embed?start=false&delayms=8000",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 473,
		interaction_type_id: 259,
		behavior: 1,
		label: "Weekend Instant Credit",
		label_i18n: "Weekend Instant Credit",
		category: "E-Value",
		help_media_urls:
			"https://docs.google.com/presentation/d/1yS0X5OnX2e_uUxw8gi3E1WD3zwXkhzfzCihVApPpyok/embed?start=false&delayms=8000",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 300,
		interaction_type_id: 272,
		behavior: 1,
		label: "Pay Loan Amount",
		label_i18n: "Pay Loan Amount",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 299,
		interaction_type_id: 266,
		behavior: 1,
		label: "Reject Loan",
		label_i18n: "Reject Loan",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 298,
		interaction_type_id: 271,
		behavior: 1,
		label: "Loan Statement",
		label_i18n: "Loan Statement",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 297,
		interaction_type_id: 264,
		behavior: 1,
		label: "Refresh Status",
		label_i18n: "Refresh Status",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 296,
		interaction_type_id: 266,
		behavior: 1,
		label: "Accept Loan Offer",
		label_i18n: "Accept Loan Offer",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 475,
		interaction_type_id: 266,
		behavior: 1,
		label: "Accept Loan Offer",
		label_i18n: "Accept Loan Offer",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 295,
		interaction_type_id: 263,
		behavior: 1,
		label: "Loans, Requests & Offers",
		label_i18n: "Loans, Requests & Offers",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 474,
		interaction_type_id: 263,
		behavior: 1,
		label: "Loans, Requests & Offers",
		label_i18n: "Loans, Requests & Offers",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 315,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "305,318",
		label: "UPI",
		label_i18n: "UPI",
		category: "E-Value",
		description:
			"Load E-value using your UPI apps like GPay, BHIM, Paytm, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "qrcode",
	},
	{
		id: 680,
		interaction_type_id: 566,
		behavior: 1,
		label: "Basic Profile Details",
		label_i18n: "Basic Profile Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/0.png",
	},
	{
		id: 1111,
		interaction_type_id: 0,
		behavior: 6,
		group_interaction_ids: "1112,1113",
		label: "UPI",
		label_i18n: "UPI",
		category: "E-Value",
		description:
			"Load E-value using your UPI apps like GPay, BHIM, Paytm, PhonePe, etc",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "qrcode",
	},
	{
		id: 681,
		interaction_type_id: 567,
		behavior: 1,
		label: "Business Details",
		label_i18n: "Business Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/2.png",
	},
	{
		id: 682,
		interaction_type_id: 568,
		behavior: 1,
		label: "Add Your References",
		label_i18n: "Add Your References",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/3.png",
	},
	{
		id: 683,
		interaction_type_id: 556,
		behavior: 1,
		label: "Personal Address Details",
		label_i18n: "Personal Address Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/1.png",
	},
	{
		id: 317,
		interaction_type_id: 0,
		behavior: 2,
		label: "Turbo E-value",
		label_i18n: "Turbo E-value",
		category: "E-Value",
		history_label: "Deposit",
		description:
			"No charges. Quickly load E-value by depositing cash in your virtual account",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "flight",
	},
	{
		id: 318,
		interaction_type_id: 0,
		behavior: 2,
		label: "View & Add Bank Account",
		label_i18n: "View & Add Bank Account",
		category: "E-Value",
		description: "View & Add Bank Account",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "account-balance",
	},
	{
		id: 684,
		interaction_type_id: 550,
		behavior: 1,
		label: "Aadhaar Consent",
		label_i18n: "Aadhaar Consent",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 707,
		interaction_type_id: 550,
		behavior: 1,
		label: "Aadhaar Consent",
		label_i18n: "Aadhaar Consent",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/5.png",
	},
	{
		id: 1113,
		interaction_type_id: 0,
		behavior: 2,
		label: "View & Add Bank Account",
		label_i18n: "View & Add Bank Account",
		category: "E-Value",
		description: "View & Add Bank Account",
		is_visible: 0,
		is_customer_visible: 1,
		icon: "account-balance",
	},
	{
		id: 685,
		interaction_type_id: 551,
		behavior: 1,
		label: "Enter Aadhar Number",
		label_i18n: "Enter Aadhaar Number",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 708,
		interaction_type_id: 551,
		behavior: 1,
		label: "Enter Aadhar Number",
		label_i18n: "Enter Aadhaar Number",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/6.png",
	},
	{
		id: 686,
		interaction_type_id: 552,
		behavior: 1,
		label: "Enter Details",
		label_i18n: "Enter Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 709,
		interaction_type_id: 552,
		behavior: 1,
		label: "Enter Details",
		label_i18n: "Enter Details",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/7.png",
	},
	{
		id: 687,
		interaction_type_id: 539,
		behavior: 1,
		label: "Upload Documents",
		label_i18n: "Upload Documents",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 688,
		interaction_type_id: 548,
		behavior: 1,
		label: "Sign Agreement",
		label_i18n: "Sign Agreement",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 738,
		interaction_type_id: 583,
		behavior: 1,
		label: "Eligibility Check",
		label_i18n: "Eligibility Check",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 739,
		interaction_type_id: 584,
		behavior: 1,
		label: "Eligibility Check",
		label_i18n: "Eligibility Check",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		logo: "https://files.eko.co.in/docs/Loan/Logo/4.png",
	},
	{
		id: 740,
		interaction_type_id: 569,
		behavior: 1,
		label: "E-Mandate",
		label_i18n: "E-Mandate",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 745,
		interaction_type_id: 593,
		behavior: 1,
		label: "E-Mandate",
		label_i18n: "E-Mandate",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 849,
		interaction_type_id: 569,
		behavior: 1,
		label: "Bank Account Verification - (Step 1/3)",
		label_i18n: "Bank Account Verification - (Step 1/3)",
		category: "E-Value",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 41,
		interaction_type_id: 0,
		behavior: 2,
		label: "Initiate Refund",
		label_i18n: "Initiate Refund",
		category: "Manage Transactions",
		description:
			"Initiate refund to customer for money-remittance, payment, etc.",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "replay",
	},
	{
		id: 328,
		interaction_type_id: 485,
		behavior: 1,
		label: "Initiate Claim Refund",
		label_i18n: "Initiate Claim Refund",
		category: "Manage Transactions",
		description:
			"Initiate cashback refund to customer for money-remittance.",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "replay",
	},
	{
		id: 158,
		interaction_type_id: 0,
		behavior: 5,
		label: "Cash Collection",
		label_i18n: "Cash Collection",
		category: "Product Stack",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "account-balance-wallet",
	},
	{
		id: 579,
		interaction_type_id: 0,
		behavior: 5,
		label: "Fund Settlement",
		label_i18n: "Fund Settlement",
		category: "Product Stack",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "account-balance-wallet",
	},
	{
		id: 142,
		interaction_type_id: 0,
		behavior: 5,
		label: "KYC",
		label_i18n: "KYC",
		category: "Product Stack",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "web-asset",
	},
	{
		id: 157,
		interaction_type_id: 0,
		behavior: 5,
		label: "API Widget",
		label_i18n: "API Widget",
		category: "Product Stack",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "widgets",
	},
	{
		id: 147,
		interaction_type_id: 0,
		behavior: 5,
		label: "Indo-Nepal Transfer",
		label_i18n: "Indo-Nepal Transfer",
		category: "Product Stack",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "developer-board",
	},
	{
		id: 551,
		interaction_type_id: 0,
		behavior: 3,
		label: "Select API Pack",
		label_i18n: "Select API Pack",
		category: "My Network",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 871,
		interaction_type_id: 0,
		behavior: 3,
		label: "Passport Renewal",
		label_i18n: "Passport Renewal",
		category: "My Network",
		description: "Renew your passport which is expired or expiring soon",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/passport-malaysia/passport.png",
	},
	{
		id: 872,
		interaction_type_id: 0,
		behavior: 3,
		label: "Passport Lost",
		label_i18n: "Passport Lost",
		category: "My Network",
		description: "Report for your lost passport",
		is_visible: 0,
		is_customer_visible: 0,
		ext_icon:
			"https://files.eko.co.in/docs/ekostore/brands/passport-malaysia/passport.png",
	},
	{
		id: 1,
		interaction_type_id: 9,
		behavior: 1,
		label: "Balance Check",
		label_i18n: "Balance Check",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 18,
		interaction_type_id: 6,
		behavior: 1,
		label: "Change PIN",
		label_i18n: "Change PIN",
		category: "My Account",
		description: "Want to change your PIN? Change it using your old PIN",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "password",
	},
	{
		id: 24,
		interaction_type_id: 412,
		behavior: 1,
		label: "Invoice Signup Status",
		label_i18n: "Invoice Signup Status",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 26,
		interaction_type_id: 412,
		behavior: 1,
		label: "Invoice Signup Status",
		label_i18n: "Invoice Signup Status",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 55,
		interaction_type_id: 10001,
		behavior: 1,
		label: "Query List",
		label_i18n: "Query List",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 95,
		interaction_type_id: 200,
		behavior: 1,
		label: "Getting Booklet Info",
		label_i18n: "Getting Booklet Info",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 98,
		interaction_type_id: 0,
		behavior: 2,
		label: "Set Your PIN",
		label_i18n: "Set Your PIN",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 99,
		interaction_type_id: 200,
		behavior: 1,
		label: "Getting Booklet Info",
		label_i18n: "Getting Booklet Info",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 100,
		interaction_type_id: 0,
		behavior: 2,
		label: "Reset PIN",
		label_i18n: "Reset PIN",
		category: "My Account",
		description: "Forgot your PIN? Reset using your registered PAN",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "password",
	},
	{
		id: 101,
		interaction_type_id: 230,
		behavior: 1,
		label: "Reset PIN",
		label_i18n: "Reset PIN",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 156,
		interaction_type_id: 243,
		behavior: 1,
		label: "Confirm Linking",
		label_i18n: "Confirm Linking",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 163,
		interaction_type_id: 243,
		behavior: 1,
		label: "Link To Distributor",
		label_i18n: "Link To Distributor",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 186,
		interaction_type_id: 10016,
		behavior: 1,
		label: "Comment",
		label_i18n: "Comment",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 187,
		interaction_type_id: 10017,
		behavior: 1,
		label: "New Comment",
		label_i18n: "New Comment",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 188,
		interaction_type_id: 10018,
		behavior: 1,
		label: "Escalate Query",
		label_i18n: "Escalate Query",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 189,
		interaction_type_id: 10019,
		behavior: 1,
		label: "Reopen Query",
		label_i18n: "Reopen Query",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 190,
		interaction_type_id: 10020,
		behavior: 1,
		label: "Close Query",
		label_i18n: "Close Query",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 195,
		interaction_type_id: 10023,
		behavior: 1,
		label: "Update Property",
		label_i18n: "Update Property",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 225,
		interaction_type_id: 549,
		behavior: 1,
		label: "Agreement Signup Status",
		label_i18n: "Agreement Signup Status",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 288,
		interaction_type_id: 460,
		behavior: 1,
		label: "Reset PIN",
		label_i18n: "Reset PIN",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 289,
		interaction_type_id: 459,
		behavior: 1,
		label: "Reset PIN",
		label_i18n: "Reset PIN",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 389,
		interaction_type_id: 327,
		behavior: 1,
		label: "View/Download Invoice",
		label_i18n: "View/Download Invoice",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 390,
		interaction_type_id: 328,
		behavior: 4,
		label: "Download Invoice",
		label_i18n: "Download Invoice",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 395,
		interaction_type_id: 333,
		behavior: 1,
		label: "Use Secret Pin",
		label_i18n: "Use Secret Pin",
		category: "My Account",
		description: "Toggle between Secret PIN and PinTwin",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "password",
	},
	{
		id: 397,
		interaction_type_id: 336,
		behavior: 1,
		label: "Configure Support Email",
		label_i18n: "Configure Support Email",
		category: "My Account",
		description: "Configure your email ID to receive updates",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "mail",
	},
	{
		id: 640,
		interaction_type_id: 553,
		behavior: 1,
		label: "Change Registered Mobile Number",
		label_i18n: "Change Registered Mobile Number",
		category: "My Account",
		description: "Update your registered mobile number",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 641,
		interaction_type_id: 555,
		behavior: 1,
		label: "Verify OTP",
		label_i18n: "Verify OTP",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 642,
		interaction_type_id: 547,
		behavior: 1,
		label: "Confirm Mobile Number Update",
		label_i18n: "Confirm Mobile Number Update",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 678,
		interaction_type_id: 653,
		behavior: 1,
		label: "Link To Distributor",
		label_i18n: "Link To Distributor",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 690,
		interaction_type_id: 549,
		behavior: 1,
		label: "Agreement Signup Status",
		label_i18n: "Agreement Signup Status",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 735,
		interaction_type_id: 10016,
		behavior: 1,
		label: "Comment",
		label_i18n: "Comment",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 741,
		interaction_type_id: 582,
		behavior: 1,
		label: "Agreement Signup Status",
		label_i18n: "Agreement Signup Status",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 811,
		interaction_type_id: 553,
		behavior: 1,
		label: "Verify Registered Mobile Number",
		label_i18n: "Verify Registered Mobile Number",
		category: "My Account",
		description: "Update your registered mobile number",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 812,
		interaction_type_id: 553,
		behavior: 1,
		label: "Add Alternate Mobile Number",
		label_i18n: "Add Alternate Mobile Number",
		category: "My Account",
		description: "Update your registered mobile number",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 813,
		interaction_type_id: 553,
		behavior: 1,
		label: "Verify Alternate Mobile Numer",
		label_i18n: "Verify Alternate Mobile Numer",
		category: "My Account",
		description: "Update your registered mobile number",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 814,
		interaction_type_id: 555,
		behavior: 1,
		label: "Verify OTP",
		label_i18n: "Verify OTP",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 815,
		interaction_type_id: 555,
		behavior: 1,
		label: "Verify OTP",
		label_i18n: "Verify OTP",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 816,
		interaction_type_id: 555,
		behavior: 1,
		label: "Verify OTP",
		label_i18n: "Verify OTP",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 817,
		interaction_type_id: 547,
		behavior: 1,
		label: "Confirm Mobile Number Update",
		label_i18n: "Confirm Mobile Number Update",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 818,
		interaction_type_id: 0,
		behavior: 3,
		label: "Is This Still Your Mobile Number?",
		label_i18n: "Is This Still Your Mobile Number?",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 823,
		interaction_type_id: 595,
		behavior: 1,
		label: "Delete Alternate Number",
		label_i18n: "Delete Alternate Number",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "smartphone",
	},
	{
		id: 13,
		interaction_type_id: 0,
		behavior: 3,
		label: "Tax Invoices",
		label_i18n: "Tax Invoices",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "description",
	},
	{
		id: 17,
		interaction_type_id: 412,
		behavior: 1,
		label: "Sign Invoice",
		label_i18n: "Sign Invoice",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 19,
		interaction_type_id: 412,
		behavior: 1,
		label: "Sign Invoice",
		label_i18n: "Sign Invoice",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 536,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids:
			"491,223,107,162,887,155,392,104,542,122,578,397,509,563,18,100,395,256,287,291,370,632,640,448",
		label: "Manage My Account",
		label_i18n: "Manage My Account",
		category: "My Account",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "settings",
	},
	{
		id: 542,
		interaction_type_id: 0,
		behavior: 3,
		label: "E-Invoice / GST",
		label_i18n: "E-Invoice / GST",
		category: "My Account",
		description:
			"View, download and approve invoices plus add your GST number",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "description",
	},
	{
		id: 543,
		interaction_type_id: 0,
		behavior: 3,
		label: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		label_i18n: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 545,
		interaction_type_id: 373,
		behavior: 1,
		label: "GST Number",
		label_i18n: "GST Number",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 546,
		interaction_type_id: 369,
		behavior: 1,
		label: "Add GST Number",
		label_i18n: "Add GST Number",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 549,
		interaction_type_id: 374,
		behavior: 1,
		label: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		label_i18n: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 887,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "878,886",
		label: "My Distributor",
		label_i18n: "My Distributor",
		category: "My Account",
		description:
			"Choose from list and search any distributor will serve you",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 578,
		interaction_type_id: 394,
		behavior: 1,
		label: "Super Saver Plans",
		label_i18n: "Super Saver Plans",
		category: "My Account",
		description: "Subscribe your plan and pay less transaction charges",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "local-offer",
	},
	{
		id: 49,
		interaction_type_id: 0,
		behavior: 2,
		label: "Query Tracker",
		label_i18n: "Query Tracker",
		category: "My Account",
		description:
			"Please share your comments/feedback with us to help us improve!",
		is_visible: 1,
		is_customer_visible: 0,
		icon: "feedback",
	},
	{
		id: 16,
		interaction_type_id: 411,
		behavior: 1,
		label: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		label_i18n: "Invoices Pending For e-Sign/Digi-Sign(GST Reimbursement)",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 656,
		interaction_type_id: 241,
		behavior: 1,
		label: "Assign Distributor",
		label_i18n: "Assign Distributor",
		category: "My Account",
		description: "Choose any distributor from list who will serve you",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 878,
		interaction_type_id: 652,
		behavior: 1,
		label: "My Distributor",
		label_i18n: "My Distributor",
		category: "My Account",
		description: "Choose any distributor from list who will serve you",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 879,
		interaction_type_id: 653,
		behavior: 1,
		label: "Unassign Distributor",
		label_i18n: "Unassign Distributor",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 881,
		interaction_type_id: 654,
		behavior: 1,
		label: "Cancel Request",
		label_i18n: "Cancel Request",
		category: "My Account",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "go",
	},
	{
		id: 886,
		interaction_type_id: 652,
		behavior: 1,
		label: "Search Distributor",
		label_i18n: "Search Distributor",
		category: "My Account",
		description: "search any distributor who will serve you",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "search",
	},
	{
		id: 888,
		interaction_type_id: 241,
		behavior: 1,
		label: "Assign Distributor",
		label_i18n: "Assign Distributor",
		category: "My Account",
		description: "Choose any distributor from list who will serve you",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "supervisor-account",
	},
	{
		id: 223,
		interaction_type_id: 300,
		behavior: 1,
		label: "Sign Agreement",
		label_i18n: "Sign Agreement",
		category: "My Account",
		description: "Agreement sign off to start doing business",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "handshake",
	},
	{
		id: 266,
		interaction_type_id: 263,
		behavior: 1,
		label: "Pre-Approved offers",
		label_i18n: "Pre-Approved offers",
		category: "My Account",
		description:
			"Check your loan status & pre-approved offer offered by lenders",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "local-offer",
		imp: 1,
	},
	{
		id: 286,
		interaction_type_id: 259,
		behavior: 1,
		label: "Create Your One Time Borrower’s Profile",
		label_i18n: "Create Your One Time Borrower’s Profile",
		category: "My Account",
		help_media_urls:
			"VV63JIE3Sco|EkoStore में आपका स्वागत है,Yc0y4ZjMMJU|How To Apply For Loan?,RRC6ZS-LVII,ZRX1AbNs0ZA,https://files.eko.co.in/docs/Loan/lending_poster.png,https://files.eko.co.in/docs/Loan/lending_poster1.png,https://files.eko.co.in/docs/Loan/lending_poster2.png,https://files.eko.co.in/docs/Loan/lending_poster3.png",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
		imp: 1,
	},
	{
		id: 620,
		interaction_type_id: 544,
		behavior: 1,
		label: "Create Your One Time Borrower’s Profile",
		label_i18n: "Create Your One Time Borrower’s Profile",
		category: "My Account",
		help_media_urls:
			"VV63JIE3Sco|EkoStore में आपका स्वागत है,Yc0y4ZjMMJU|How To Apply For Loan?,RRC6ZS-LVII,ZRX1AbNs0ZA,https://files.eko.co.in/docs/Loan/lending_poster.png,https://files.eko.co.in/docs/Loan/lending_poster1.png,https://files.eko.co.in/docs/Loan/lending_poster2.png,https://files.eko.co.in/docs/Loan/lending_poster3.png",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "loan",
	},
	{
		id: 287,
		interaction_type_id: 0,
		behavior: 3,
		label: "Request E-value or View & Add Bank Account",
		label_i18n: "Request E-value or View & Add Bank Account",
		category: "My Account",
		description: "Add your bank account for E-value purpose",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "settings",
	},
	{
		id: 290,
		interaction_type_id: 472,
		behavior: 1,
		label: "Change AePS Device",
		label_i18n: "Change AePS Device",
		category: "My Account",
		description: "You can update your new AePS device",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "fingerprint",
		imp: 1,
	},
	{
		id: 291,
		interaction_type_id: 471,
		behavior: 1,
		label: "Change AePS Device",
		label_i18n: "Change AePS Device",
		category: "My Account",
		description: "You can update your new AePS device",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "fingerprint",
		imp: 1,
	},
	{
		id: 35,
		interaction_type_id: 185,
		behavior: 1,
		label: "E-value History",
		label_i18n: "E-value History",
		category: "Invitations",
		is_visible: 0,
		is_customer_visible: 0,
	},
	{
		id: 348,
		interaction_type_id: 491,
		behavior: 1,
		label: "Download ID Card",
		label_i18n: "Download ID Card",
		category: "COVID-19",
		description: "Generate your essentials service ID card",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 448,
		interaction_type_id: 0,
		behavior: 7,
		group_interaction_ids: "438,348,621,622",
		label: "COVID-19 Essentails",
		label_i18n: "COVID-19 Essentials",
		category: "COVID-19",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "corona-protect",
	},
	{
		id: 622,
		interaction_type_id: 0,
		behavior: 5,
		label: "Download Essential Services Certificate",
		label_i18n: "Download Essential Services Certificate",
		category: "COVID-19",
		description:
			"Download Essential Services Certificate to run your business during COVID",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 349,
		interaction_type_id: 492,
		behavior: 4,
		label: "Download ID Card",
		label_i18n: "Download ID Card",
		category: "COVID-19",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
	{
		id: 621,
		interaction_type_id: 0,
		behavior: 5,
		label: "Important Information",
		label_i18n: "Important Information",
		category: "COVID-19",
		description: "Get important information regarding Covid-19",
		is_visible: 0,
		is_customer_visible: 0,
		icon: "user-card",
	},
];
