export const BusinessDashboardData = [
	{
		response_status_id: 1,
		data: {
			client_ref_id: "202301031354123456",
			OrgId: "",
			user_code: "99010036",
			source: "",
			dashboard_details: [
				{
					topPanel: {
						totalDistributers: {
							totalDistributers: "23",
							increaseOrDecrease: 0,
						},
						activeDistributers: {
							activeDistributers: "0",
							increaseOrDecrease: 1,
						},
						grossTransactionValue: {
							grossTransactionValue: "660516",
							increaseOrDecrease: -0.8,
						},
						raCases: {
							raCases: "0",
							increaseOrDecrease: -100,
						},
					},
					earningOverview: {
						gtv: {
							amount: "541669",
							lastPeriod: "541669",
							increaseOrDecrease: 0,
						},
						transactions: {
							transactions: "448",
							lastPeriod: "448",
							increaseOrDecrease: 2,
						},
						activeAgents: {
							active: "6",
							lastPeriod: "7",
							increaseOrDecrease: -14.3,
						},
						onboardedAgents: {
							onboarded: "6",
							lastPeriod: "6",
							increaseOrDecrease: 0,
						},
						raCases: {
							raCases: "0",
							lastPeriod: "18",
							increaseOrDecrease: -100,
						},
					},
					successRate: {
						dmt: {
							Percentage: 15.9,
						},
						bbps: {
							Percentage: 78.3,
						},
						aepsCashout: {
							Percentage: 35.3,
						},
						aepsMiniStatement: {
							Percentage: 66.7,
						},
						accountVerification: {
							Percentage: 29.3,
						},
					},
					topMerchants: [
						{
							name: "Rohit",
							gtv: "820068",
							totalTransactions: "185",
							status: "Active",
							raCases: "Rohit",
							onboardingDate: "2021-06-21",
							distributorMapped: "GAURAVJI KUMAR",
						},
						{
							name: "KAIRA KHAN",
							gtv: "272730",
							totalTransactions: "23",
							status: "Active",
							raCases: "KAIRA KHAN",
							onboardingDate: "2020-07-13",
							distributorMapped: "KAIRA KHAN",
						},
						{
							name: "PRAKASH RAM JHUNJHUNWALA",
							gtv: "221698",
							totalTransactions: "84",
							status: "Active",
							raCases: "PRAKASH RAM JHUNJHUNWALA",
							onboardingDate: "2022-03-24",
							distributorMapped: "Gaurav Malik",
						},
						{
							name: "JIVESH KUMAR GARG",
							gtv: "159066",
							totalTransactions: "48",
							status: "Active",
							raCases: "JIVESH KUMAR GARG",
							onboardingDate: "2022-06-27",
							distributorMapped: "10i Commerce",
						},
						{
							name: "Airwave Teleservices",
							gtv: "59508",
							totalTransactions: "12",
							status: "Active",
							raCases: "Airwave Teleservices",
							onboardingDate: "2021-01-07",
							distributorMapped: "Airwave Teleservices",
						},
						{
							name: "10i Commerce",
							gtv: "59378",
							totalTransactions: "7",
							status: "Active",
							raCases: "10i Commerce",
							onboardingDate: "2021-09-17",
							distributorMapped: "10i Commerce",
						},
						{
							name: "Gaurav Rao",
							gtv: "39861",
							totalTransactions: "24",
							status: "Active",
							raCases: "Gaurav Rao",
							onboardingDate: "2021-05-27",
							distributorMapped: "Test Distributor 1",
						},
						{
							name: "Airwave Teleservices",
							gtv: "27974",
							totalTransactions: "27",
							status: "Active",
							raCases: "Airwave Teleservices",
							onboardingDate: "2021-12-29",
							distributorMapped: "Airwave Teleservices",
						},
						{
							name: "PRAKASH RAM JHUNJHUNWALA",
							gtv: "4638",
							totalTransactions: "4",
							status: "Active",
							raCases: "PRAKASH RAM JHUNJHUNWALA",
							onboardingDate: "2018-12-01",
							distributorMapped: "Rohit",
						},
						{
							name: "UserName Dist",
							gtv: "2746",
							totalTransactions: "4",
							status: "Active",
							raCases: "UserName Dist",
							onboardingDate: "2022-06-29",
							distributorMapped: "UserName Dist",
						},
					],
				},
			],
		},
		response_type_id: 1843,
		message: "Dashboard Displayed!",
		status: 1843,
	},
];

export const OnboardingDashboardData = [
	{
		response_status_id: 1,
		data: {
			client_ref_id: "202301031354123456",
			user_code: "99029899",
			initiator_id: "9911572989",
			org_id: "",
			onboarding_dashboard_details: [
				{
					topPanel: {
						partialAccount: "94",
						businessDetailsCaptured: "1",
						aadhaarCaptured: "11",
						panCaptured: "5",
						agreementSigned: "11",
						onboarded: "25",
						nonTransactiingLive: "3",
					},
				},
				{
					onboardedMerchants: [
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000345",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-23",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000353",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-06",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000359",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-09",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000360",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-15",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000350",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-05-25",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "Jivesh Kumar Garg",
							ekoCode: "10000366",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "Jivesh Kumar Garg",
							ekoCode: "10000366",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "Jivesh Kumar Garg",
							ekoCode: "10000366",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "Jivesh Kumar Garg",
							ekoCode: "10000366",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "Jivesh Kumar Garg",
							ekoCode: "10000366",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000368",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000368",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000368",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000368",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000367",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-06-27",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000406",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-07-11",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000406",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-07-11",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000406",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-07-11",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
						{
							merchantName: "JIVESH KUMAR GARG",
							ekoCode: "10000406",
							city: "North West Delhi",
							state: "National Capital Territory of Delhi (UT)",
							businesstType: "4",
							onboardedOn: "2022-07-11",
							businessName: "R J",
							daysinFunnel: "68 days ago",
							businessDetailsCaptured: "12 days ago",
							aadhaarCaptured: "32 days ago",
							panCaptured: "12 days ago",
							agreementSigned: "11 days ago",
							onboarded: "11 days ago",
							transacting: "2 days ago",
						},
					],
				},
			],
			source: "",
		},
		response_type_id: 1840,
		message: "Onboarding Dashboard Display!",
		status: 1840,
	},
];
