import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Index() {
	return (
		<div>
			<h1>hello team</h1>
			{/* <Head>
				<title>Eko Admin</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box bg="primary.light">Hello World</Box> */}
		</div>
	);
}
