import { Box } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Eko Admin</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box bg="primary.light"> Hello</Box>
			<Box bg="accent.DEFAULT"> asdfasdf</Box>
			<Box bg="secondary.dark"> asdfasdfasd</Box>
		</>
	);
}
